apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*  # all the file we want to apply
      - ./infra/k8s-dev/*
build:
  local:  # when we build an image do not push to docker hub which is the default behavior
    push: false
  artifacts:  ## all the things that are going to be build
    - image: jerry377/auth
      context: auth # the name of the folder that contains all the code for the image
      docker: # telling skaffold what docker file to use
        dockerfile: Dockerfile
      sync:  # to tell skaffold how to handle any change of a file inside auth dir
        manual:
          - src: 'src/**/*.ts' #to watch for all the files that ends with .ts
            dest: . # dest is where to sync the changed files and . means take from you found and put in the corresponding path inside the container
    - image: jerry377/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: jerry377/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: jerry377/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: jerry377/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: jerry377/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .