apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-node
spec:
  type: NodePort
  selector:
    app: auth-mongo
  ports:
    - name: auth-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-node
spec:
  type: NodePort
  selector:
    app: tickets-mongo
  ports:
    - name: tickets-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017